version: '3.8'

networks:
  bookmarks:

services:
  &db db:
    image: postgres:16
    restart: always
    hostname: postgres
    env_file:
      - '.env'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_bookmarks:/var/lib/postgresql
    networks:
      - bookmarks

volumes:
  postgres_data_bookmarks: